Update teacher.lua
Illarion-eV/Illarion-Content pull request #317
Opened 2022-02-03 19:15 UTC by dayjaby

Bombs use sapphire gemdust, not emerald.

2022-02-03 19:16 UTC, dayjaby commented
Huh, no idea where the many line changes come from. Probably some `\r\n` vs `\n` issue. Did the edit on github itself.

2022-02-03 19:27 UTC, estralis commented
Github uses the wrong encoding, see code review.

2022-02-04 12:53 UTC, estralis requested changes
Please change encoding to ISO 8859-1.

2022-02-04 13:44 UTC, dayjaby commented
Ok, lesson learned never to use the github editor again :D

2022-02-06 16:32 UTC, estralis commented
It's not your fault, we would also love to use the GitHub editor. But the decision what encoding is used was taken before we used GitHub and changing it now would be a significant task with not benefit for the players.

2022-07-24 07:22 UTC, merged